version: '3.7'

services:
    dev:
        image: golang:1.19
        container_name: go-template
        volumes:
            - .:/app
        working_dir: /app
        command: tail -F anything
        ports:
            - 10001:9000